### ISSUE TITLE
export=VAR=test

### ISSUE THREAD

**Issue by sjafarza** [sjafarza/minishell#1]
minishell result : Command not found: export=VAR=test

bash    result : nothing (prompt)

**Comment by Psycokwet** [comment]
C'est normal, c'est pas un bug.
![image](https://user-images.githubusercontent.com/14911120/150646061-6c619bcf-8d32-4282-9b13-c27631360d6f.png)

**Comment by Psycokwet** [comment]
On gere pas nous les = sauvage, que ceux dans export corrects
