### ISSUE TITLE
echo $$

### ISSUE THREAD

**Issue by sjafarza** [sjafarza/minishell#10]
bash : 3106
minishell : $$

**Comment by Psycokwet** [comment]
Pour moi c'est pas une variable a gerer, donc, on fait quoi? Pour l'instant j'ai beaucoup a faire sur les redirection, je te laisse voir si on fait quelque chose de ça :)

**Comment by sjafarza** [comment]
j'ai le posé dans discord , on voir les return des gens ,

**Comment by sjafarza** [comment]
j'ai reçu la réponse de 2 qui déjà le validé ( la seule variable spéciale qu'il faut gérer c'est $), donc je ferme l'issue
