### ISSUE TITLE
ls | grep Makefile

### ISSUE THREAD

**Issue by sjafarza** [sjafarza/minishell#15]
bash : Makefile

minishell : ( this result  +   waiting in an while ) :

mishell$ ls | grep file
RESULT 0
        parsed_group stack, size : 3
PRINT CELL TYPE 8:
0[ls]
1[]
PRINT CELL TYPE 2:
0[|]
PRINT CELL TYPE 8:
0[grep]
1[file]
        End parsed_group stack : 3
RESULT exec parsed 0
        Pipex stack, size : 2
PRINT CELL :
0[ls]
1[]
PRINT CELL :
0[grep]
1[file]
        End Pipex stack : 2
full_cmd in bash_cmd = /bin/grep
FULL_CMD : /bin/grep
full_cmd in bash_cmd = /bin/ls
FULL_CMD : /bin/ls
ls: impossible d'accéder à '': Aucun fichier ou dossier de ce type

**Comment by Psycokwet** [comment]
J'ai corrigé la boucle infini y'a quelques jours :) 
Pour la redirection elle même, c'est encore en travaux, mais ça on le sais ! :)
