### ISSUE TITLE
echo $COLORTERM$$hey

### ISSUE THREAD

**Issue by sjafarza** [sjafarza/minishell#29]
bash : truecolor7067hey ( truecolor    +  7067     +   hey)

minishell : truecolor

**Comment by Psycokwet** [comment]
Ce cas pose des prob que je ne comprend pas encore, je me garde ça sous la main pour plus tard

**Comment by sjafarza** [comment]
pour lancer de cette commande (echo truecolor7067hey) , il y résultat différant entre minishell et bash:
résultat in bash pour  (echo truecolor7067hey) est ( truecolor7067hey)
et
résultat in minishell pour  (echo truecolor7067hey) est ( truecolor)

**Comment by Psycokwet** [comment]
Vu qu'on gere pas la variable speciale $$ pour moi c'est bon, si on doit la gerer c'est une autre histoire, mais maintenant, le reste est correct en tous cas
