### ISSUE TITLE
cd ''

### ISSUE THREAD

**Issue by sjafarza** [sjafarza/minishell#8]
1) cd ''

**Comment by sjafarza** [comment]
cd '' = cd 'space vide '  
bash afiiche rien mais minishell  affiche "mshell: cd: : Aucun fichier ou dossier de ce type"

**Comment by Psycokwet** [comment]
Merci, je gere ça dès que je peux :)

**Comment by sjafarza** [comment]
C'est bon , est parreille que BASH, Merci
